# YAML file for a multi-stage pipeline
trigger:
  - master

stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'windows-latest'
        steps:
          - script: echo "Building the application..."
            displayName: "Build the application"

  - stage: Test
    jobs:
      - job: Test
        dependsOn: Build
        pool:
          vmImage: 'windows-latest'
        steps:
          - script: echo "Running tests..."
            displayName: "Run tests"

  - stage: Deploy
    dependsOn: Test
    jobs:
      - job: Deploy
        pool:
          vmImage: 'windows-latest'
        steps:
          - script: echo "Deploying the application..."
            displayName: "Deploy the application"